### ISSUE TITLE
Чего хочется

### ISSUE THREAD

**Issue by 3y3** [Katochimoto/mops#1]
Инкапсуляция аспектов:

> контекст опять же клевенький :slightly_smiling_face: только один и неизменяемый

Отлично значит очередь отвечает за сохранение контекста, пусть этим и занимается, незачем расширять ее неймспейс ради простоты написания:

``` js
const queue = new MOPS.Queue();

queue(context) // А еще лучше queue(new MOPS.Context({ ... }))
    .add(action1, params1)
    .add(action2, params2)
    .cond() // <-- Остановите это, с каких пор у нас очереди ветвятся?
    .start() // <-- Зачем? Очередь может выполнять действия сразу в add
```

Пусть action отвечает за логирование и что-то еще что ему положено, но непонятно зачем класть его в какой-то неймспейс, который потом может быть скопирован и расширен. У нас же есть объектное программирование.

``` js
function CommonActions() {}

function reply(params) { ... }

CommonActions.prototype = {
    reply: new MOPS.Action('reply', reply),

    replyAll: new MOPS.Action('replyAll', function(params) { return reply(params); })
};

function ExtraActions() {}

ExtraActions.prototype = Object.create(CommonActions.prototype, {
    extraAction: {
        value: new MOPS.Action('extraAction', function(params) { ... })
    }
});
```

Сам action тогда строится примерно так:

``` js
MOPS.Action = function(name, action) {
    /**
     * @this {MOPS.Context}
     */
    return function(params) {
        const timer = this.start(name, params);

        function success(result) {
             timer.stop();
             this.log(name, params, timer);
             return;
        }

        function error(error) {
             timer.stop();
             this.error(name, params, timer, error);
             return;
        }
        return Promise.resolve()
                .then(function() {
                    return action(params);
                })
                .then(success, error)
                .then(resolve, reject)
    }
};

```

**Comment by 3y3** [comment]
В данном случае https://github.yandex-team.ru/Daria/liza/blob/daria-57027/mail/modules/mail/actions/reply.js#L63
залогируется вызов экшена `reply`, а не `replyAll`

**Comment by Katochimoto** [comment]
> Остановите это, с каких пор у нас очереди ветвятся?

эти очереди ветвятся )
это архиважно для описания мопсов

**Comment by 3y3** [comment]
`Queue.prototype.add` выглядит примерно так:

``` js
/**
 * @param {MOPS.Action} action
 * @param {Object} params
 */
Queue.prototype.then = function(action, params) {
    return action.call(this.context, params);
};
```

**Comment by 3y3** [comment]
> эти очереди ветвятся )

Почему ветвление должно быть частью очереди?
Я не против ветвления, но это не область ответственности очереди.

**Comment by Katochimoto** [comment]
``` js
const queue = new MOPS.Queue(context);

queue
    .then(action1)
```

так лучше

**Comment by Katochimoto** [comment]
> Почему ветвление должно быть частью очереди?

а частью чего?

**Comment by Katochimoto** [comment]
> У нас же есть объектное программирование.

ну собственно там это и происходит
просто сокращенно написано

**Comment by 3y3** [comment]
Ну такой вариант у меня тоже был =)

Допустим я осознал зачем нужен старт

``` js
queue(context) // А еще лучше queue(new MOPS.Context({ ... }))
    .add(action1, params1)
    .add(action2, params2)
    .add(cond ? queue1 : queue2)
```

``` js
/**
 * @param {MOPS.Action|MOPS.Queue} action
 * @param {Object} params
 */
Queue.prototype.add = function(action, params) {
    if (action instanceof MOPS.Queue) {
      return action.start();
    }

    return action.call(this.context, params);
};
```

**Comment by 3y3** [comment]
А еще лучше привести Action и Queue к одному интерфейсу и всегда вызывать `action.start()`

**Comment by Katochimoto** [comment]
а теперь надо ещё
результат выполнения обработать и запустить start для вложенной очереди

**Comment by Katochimoto** [comment]
`CommonActions` - это аналог mops (декларация, наследование)
Очередь часть мопса только ради того, чтобы сразу из набора начинать выполнение

**Comment by Katochimoto** [comment]
ты все верно предлагаешь, но это длиннее 
кажется что собрав всё воедино получается то что получилось

**Comment by 3y3** [comment]
Антон, я хочу подчеркнут, что я не пытаюсь переизобрести твой подход, я именно пытаюсь его декомпозировать, чтобы одно хранилище не отвечало за разные функции.

**Comment by 3y3** [comment]
Да, то что я пишу - чуть длиннее, но и более контролируемое

**Comment by Katochimoto** [comment]
я именно этого и добивался.. (
быстро создал клон, набил методами и пошел запускать

**Comment by Katochimoto** [comment]
в каком смысле более контролируемое?

**Comment by Katochimoto** [comment]
разделение ответственности - ок да

**Comment by Katochimoto** [comment]
`cond` ты не правильно понял
это не условное ветвление, а условная вставка шага

**Comment by Katochimoto** [comment]
в общем, что имеем
- `mops.Queue` - `then`, `catch`, `always`, `start`
- `mops.Action`
- `mops.Context`

так? то есть по сути получается почти то что есть, за исключением неявного объявления экшена в экземпляре `mops`?

`add` в очередь не катит, экшен выполняется либо по resolve ветке, либо по reject

у `mops.Action` `start` не понятно зачем. 
это удобно в моем варианте, когда у тебя вызов экшена позволяет продолжать цепочку
с отделение `Queue` от декларации это не удобно

но мне правда не нравится отрывать декларацию от очереди :(
сейчас это тебе 4мя буквами дает возможность вызвать объявленный метод и запустить очередь

я бы про это ребят спросил
у тебя всё разделено и зачем это понятно
но это неудобно :(

**Comment by Katochimoto** [comment]
можешь написать как будет выглядеть то, что сейчас в README?
просто функции в очередь я бы тоже хотел добавлять, но так, чтобы они вели себя так же как и экшены

**Comment by Katochimoto** [comment]
если то что выше имеем ок, тогда подумать можно)
но я точно не хочу терять в очереди логику `then`, `catch`, `always`
без этого мопсы будет адово труднее попилить

`cond` можно опустить

**Comment by Katochimoto** [comment]
на такое согласны?
https://github.com/Katochimoto/mops/blob/rc-3/README.md

разделение `mops.Action` будет плюсом при переходе на commonjs
так полностью поддерживаю

**Comment by Katochimoto** [comment]
объясню зачем `start` у очереди.
мне очень хочется иметь `then`
но наличие этого метода автоматом делает из объекта промис, 
при этом первый аргумент метода считается **resolve** а второй **reject** методом.
а это полностью меняет задуманный интерфейс, когда аргументами прилетают обработчики, а не методы установки состояния!

возвращать настоящий промис в `new mops.Queue()` я не могу, потому что надо экшены в контексте вызывать. 
да и `then` у меня отличается от промисного аргументами, это важно.
поэтому приходится вначале заполнять очередь, а после `start` запускать цепочку промисов

**Comment by Katochimoto** [comment]
done
https://github.com/Katochimoto/mops/pull/2
